/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project.sdnl.gui;

import project.sdnl.graphUtils.AngkotGraph;

import javax.swing.*;
import java.util.List;

/**
 *
 * @author HP
 */
public class RuteTerpendek extends javax.swing.JFrame {

    private final AngkotGraph graph = new AngkotGraph(20);

    /**
     * Creates new form RuteTerpendek
     */
    public RuteTerpendek() {
        initComponents();
        initializeGraph();

    }

    private void initializeGraph() {
        // Add graph edges here, similar to the main method in the console version
        graph.addEdge("Patuk", "Ngawen", 2);
        graph.addEdge("Patuk", "Wonosari", 6);
        graph.addEdge("Ngawen", "Wonosari", 4);
        graph.addEdge("Ngawen", "Karangmojo", 2);
        graph.addEdge("Ngawen", "Semin", 7);
        graph.addEdge("Wonosari", "Semin", 8);
        graph.addEdge("Wonosari", "Sambirejo", 4);
        graph.addEdge("Wonosari", "UGM Kampus Geologi", 10);
        graph.addEdge("Karangmojo", "Cawas", 7);
        graph.addEdge("Karangmojo", "Semin", 1);
        graph.addEdge("Sambirejo", "Semin", 4);
        graph.addEdge("Sambirejo", "Bayat", 7);
        graph.addEdge("Sambirejo", "Gereja Kelor", 6);
        graph.addEdge("Sambirejo", "Masjid Ngawen", 3);
        graph.addEdge("Semin", "Cawas", 3);
        graph.addEdge("Semin", "Bayat", 2);
        graph.addEdge("Cawas", "Bayat", 2);
        graph.addEdge("Cawas", "Nologaten", 5);
        graph.addEdge("Cawas", "RS Panti Rahayu", 6);
        graph.addEdge("Bayat", "RS Panti Rahayu", 3);
        graph.addEdge("Bayat", "Gereja Kelor", 3);
        graph.addEdge("Gereja Kelor", "RS Panti Rahayu", 1);
        graph.addEdge("Gereja Kelor", "Vihara Candirejo", 1);
        graph.addEdge("Gereja Kelor", "Masjid Ngawen", 2);
        graph.addEdge("Masjid Ngawen", "Vihara Candirejo", 4);
        graph.addEdge("Masjid Ngawen", "UGM Kampus Geologi", 3);
        graph.addEdge("RS Panti Rahayu", "Vihara Candirejo", 3);
        graph.addEdge("RS Panti Rahayu", "Nologaten", 2);
        graph.addEdge("RS Panti Rahayu", "Candirejo", 3);
        graph.addEdge("Nologaten", "Candirejo", 5);
        graph.addEdge("Candirejo", "Pasar Sambeng", 6);
        graph.addEdge("Candirejo", "Vihara Candirejo", 3);
        graph.addEdge("UGM Kampus Geologi", "Pasar Sambeng", 3);
        graph.addEdge("Vihara Candirejo", "Pasar Sambeng", 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jMulaiButton = new javax.swing.JToggleButton();
        jResetButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setText("RUTE TERPENDEK ANGKOT GUNUNG KIDUL");

        jLabel2.setText("Posisi Awal");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Tujuan Akhir");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Tampilkan Hasil");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jMulaiButton.setText("Mulai");
        jMulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMulaiButtonActionPerformed(evt);
            }
        });

        jResetButton1.setText("Reset");

        jToggleButton2.setText("Keluar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField4)
                    .addComponent(jTextField1)
                    .addComponent(jTextField5))
                .addGap(8, 8, 8))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jMulaiButton)
                .addGap(65, 65, 65)
                .addComponent(jResetButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton2)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMulaiButton)
                    .addComponent(jResetButton1)
                    .addComponent(jToggleButton2))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jMulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMulaiButtonActionPerformed
        // TODO add your handling code here:
        try {
            String startDestination = jTextField4.getText();
            String finishDestination = jTextField1.getText();
            List<String> shortestPath = graph.findShortestPath(startDestination, finishDestination);

            System.out.println("Intermediate Vertices:");

            if (shortestPath != null) {
                jTextField5.setText(String.join(" -> ", shortestPath));
            }

        } catch (ArrayIndexOutOfBoundsException exception) {
            JOptionPane.showMessageDialog(null, "Vertex Invalid");
        }//GEN-LAST:event_jMulaiButtonActionPerformed
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RuteTerpendek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RuteTerpendek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RuteTerpendek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RuteTerpendek.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RuteTerpendek().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JToggleButton jMulaiButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jResetButton1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton2;
    // End of variables declaration//GEN-END:variables
}
